version: '3.8'

services:
  mcp-chatwoot:
    build:
      context: ../../mcp-chatwoot
      dockerfile: Dockerfile
    container_name: mcp-chatwoot
    restart: unless-stopped
    environment:
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8004
      - MCP_TRANSPORT=sse
      - MCP_SERVICE_NAME=mcp-chatwoot
      - CHATWOOT_BASE_URL=${CHATWOOT_BASE_URL:-http://chatwoot:3000}
      - CHATWOOT_ACCESS_TOKEN=${CHATWOOT_ACCESS_TOKEN}
      - CHATWOOT_HMAC_KEY=${CHATWOOT_HMAC_KEY}
      - CHATWOOT_INBOX_IDENTIFIER=${CHATWOOT_INBOX_IDENTIFIER}
      - MCP_CREW_URL=${MCP_CREW_URL:-http://mcp-crew:8000}
      - MCP_CREW_TOKEN=${MCP_CREW_TOKEN}
    ports:
      - 8004:8004
      - 8084:8080  # Porta para o health check
    networks:
      - ai-stack
    volumes:
      - ../../mcp-chatwoot/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  ai-stack:
    external: true
