## Configuração para o Cliente 4 - Domínio de Varejo
## Este arquivo define todas as configurações específicas para o Cliente 4 no domínio de varejo

version: "2.1"
metadata:
  domain: retail
  account_id: "account_4"
  client_name: "SuperCompras Varejo"
  description: "Rede de lojas com diversidade de produtos para o lar e uso pessoal"
  inherit: "_base"  # Herda configurações base

# Configurações específicas dos agentes para o domínio de varejo
agents:
  retail_expert:
    type: SalesAgent
    config:
      role: "Consultor de Compras"
      goal: "Auxiliar clientes na escolha de produtos ideais para suas necessidades"
      backstory: |
        Especialista em produtos de varejo com amplo conhecimento sobre características,
        qualidade e utilização de produtos para o lar e uso pessoal.
    tools:
      - product_catalog
      - customer_preferences
      - sale_recommender
    plugins:
      - name: retail_advisor
        version: 1.2
        config:
          product_categories: ["eletrônicos", "eletrodomésticos", "utensílios", "decoração"]
          special_offers: true

  home_specialist:
    type: ProductAgent
    config:
      role: "Especialista em Produtos para o Lar"
      goal: "Recomendar produtos adequados para cada ambiente da casa"
      backstory: |
        Decorador(a) de interiores com experiência em organização e design de ambientes.
        Conhecimento especializado em produtos que combinam funcionalidade e estética.
    tools:
      - home_catalog
      - room_planner
      - product_matcher
    plugins:
      - name: home_advisor
        version: 1.1
        config:
          room_types: ["cozinha", "sala", "quarto", "banheiro", "área externa"]
          style_preferences: ["moderno", "clássico", "rústico", "minimalista"]
