version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: chatwoot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-chatwoot_redis_password}
    networks:
      - chatwoot-network

volumes:
  redis-data:
    name: chatwoot-redis-data

networks:
  chatwoot-network:
    name: chatwoot-network
    external: false
