version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: chatwoot-qdrant
    restart: unless-stopped
    volumes:
      - ./qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"  # API e interface web
      - "6334:6334"  # Comunicação entre nós (gRPC)
    environment:
      - QDRANT_ALLOW_CORS=true
    networks:
      - chatwoot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  chatwoot-network:
    external: true
