version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: chatwoot-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispassword} --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chatwoot-network
    restart: unless-stopped

volumes:
  redis_data:
    name: chatwoot-redis-data

networks:
  chatwoot-network:
    external: true
    name: chatwoot-network
