version: '3.8'

services:
  # MCP-Odoo
  mcp-odoo:
    build:
      context: ./mcp-odoo
    ports:
      - "8000:8000"
    environment:
      - ODOO_URL=${ODOO_URL:-http://localhost:8069}
      - ODOO_DB=${ODOO_DB:-odoo}
      - ODOO_USERNAME=${ODOO_USERNAME:-admin}
      - ODOO_PASSWORD=${ODOO_PASSWORD:-admin}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    volumes:
      - ./mcp-odoo:/app
    depends_on:
      - redis
    restart: unless-stopped

  # MCP-MongoDB
  mcp-mongodb:
    build:
      context: ./mcp-mongodb
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
      - MONGODB_DB=${MONGODB_DB:-config}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    volumes:
      - ./mcp-mongodb:/app
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped

  # MCP-Qdrant
  mcp-qdrant:
    build:
      context: ./mcp-qdrant
    ports:
      - "8002:8000"
    environment:
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    volumes:
      - ./mcp-qdrant:/app
    depends_on:
      - redis
      - qdrant
    restart: unless-stopped

  # Redis (para cache e comunicação entre serviços)
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispassword}
    volumes:
      - redis-data:/data
    restart: unless-stopped

  # MongoDB (para armazenamento de configurações)
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-mongopassword}
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

  # Qdrant (para armazenamento vetorial)
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

  # API para orquestração de crews
  crewai-api:
    build:
      context: ../src/crewai
    ports:
      - "8003:8000"
    environment:
      - MCP_ODOO_URL=http://mcp-odoo:8000
      - MCP_MONGODB_URL=http://mcp-mongodb:8000
      - MCP_QDRANT_URL=http://mcp-qdrant:8000
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispassword}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    volumes:
      - ../src/crewai:/app
    depends_on:
      - mcp-odoo
      - mcp-mongodb
      - mcp-qdrant
      - redis
    restart: unless-stopped

volumes:
  redis-data:
  mongodb-data:
  qdrant-data:
