version: '3.8'

services:
  api:
    build: .
    container_name: config-service-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/config_service
      - API_KEY=development-api-key
      - DEBUG=true
      - ENVIRONMENT=development
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - db
    volumes:
      - ./:/app
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: config-service-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=config_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
