version: '3.8'

services:
  mongodb:
    image: mongo:6.0-focal
    container_name: ai-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
      - MONGO_INITDB_DATABASE=config_service
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - 27017:27017
    networks:
      - ai-stack
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongo-express:
    image: mongo-express:latest
    container_name: ai-mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin_password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin_password@mongodb:27017/admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=express_password
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://admin:express_password@localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 8082:8081
    networks:
      - ai-stack
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
    name: ai_stack_mongodb_data

networks:
  ai-stack:
    external: true
