version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - chatwootai_network_public

volumes:
  redis_data:
    name: redis_data

networks:
  chatwootai_network_public:
    external: true
