account_id: account_1
description: "Configura\xE7\xE3o para Cliente"
integrations:
  facebook:
    access_token_ref: fb_token_account_1
    app_secret_ref: fb_secret_account_1
  instagram:
    access_token_ref: ig_token_account_1
  mcp:
    config:
      credential_ref: account_1-00bfe67a
    type: odoo-mcp
  mercado_livre:
    access_token_ref: ml_token_account_1
    client_secret_ref: ml_secret_account_1
  qdrant:
    collection: business_rules_account_1
  redis:
    prefix: account_1
name: Cliente
