account_id: account_1
credentials:
  account_1-00bfe67a: ENC:Z0FBQUFBQm9HWGlRbGQwazBkM092czhZanA1MWhlUWtUZWlHM0JVMnFoYmZaM283czVQLWdUMlRTbmxrSDFkMjFxbV91Slk0bm9BUmg4MWdSR05kRWNFMTBJdkR1dDFhR3c9PQ==
  fb_secret_account_1: ENC:Z0FBQUFBQm9HWGlRblZBZkU3NEpKUkRoMDA4ZDdkV1dkd1loT1ktdXJydU04WHlvSENGZG9MUmJiTU1hWm5rYUM0NHRoOGxfYmVRb3NfTUtoZVp4YlpCelJBYzRzZUlKZXc9PQ==
  fb_token_account_1: ENC:Z0FBQUFBQm9HWGlRUVpyZ3FYQ3BkbWhOX1VLcGhxblV3d2hzdmpDSHJtRnM2VGJUVUFqWFlqeHRvZXQ4Z1g2djlaY3F0NGh3S2JOdTg3bldmbXlHcVhpdl94LUpVVkhOS0E9PQ==
  ig_token_account_1: ENC:Z0FBQUFBQm9HWGlRYnhPT2R6dmpoZHRfT0d0RFhDWVF1X29iMkNvc0x6a0RlT3RKdTlVMXpId1ptVXJtQTRrY2xBVFBTMkdoYXZ1cGlvUnA5TG5DUnFuVndmM3NiSUczNHc9PQ==
  ml_secret_account_1: ENC:Z0FBQUFBQm9HWGlRTFpYcC1KR043Ynh2c2FuU0FldkRWTlVLaElzakdCamJ5VDVlV3FNNU9IdmdGMDl1TFpIRHdEcDdjdGJkWWs4SkJZSXZWQkpqc3ROcjM2ZW1QU1RRTkE9PQ==
  ml_token_account_1: ENC:Z0FBQUFBQm9HWGlRNnlhQkZSTnFCN2tkclQxRlYwaHN4YURqVlV6QXcwVXh5TGRPUXA0bUE0SXRiMWhxTjFpZnlTN0UtRGhCUzNGeXdtSVpuZFdFOGdZbDc5THRRc3lzTmc9PQ==
