## Configuração para o Cliente 3 - Domínio de Saúde
## Este arquivo define todas as configurações específicas para o Cliente 3 no domínio de saúde

version: "2.1"
metadata:
  domain: health
  client_id: "client_3"
  client_name: "Vida Saudável Farmácias"
  description: "Rede de farmácias especializada em produtos naturais e suplementos"
  inherit: "_base"  # Herda configurações base

# Configurações específicas dos agentes para o domínio de saúde
agents:
  health_advisor:
    type: HealthAgent
    config:
      role: "Consultor de Bem-estar"
      goal: "Auxiliar clientes na escolha de produtos para saúde e bem-estar"
      backstory: |
        Profissional com formação em farmácia e especialização em produtos naturais.
        Você tem amplo conhecimento sobre suplementos e vitaminas para melhorar a qualidade de vida.
    tools:
      - supplement_catalog
      - wellness_recommender
      - nutrition_analyzer
    plugins:
      - name: natural_health_advisor
        version: 1.1
        config:
          health_concerns: ["imunidade", "energia", "sono", "digestão", "articulações"]
          dietary_preferences: ["vegetariano", "vegano", "sem glúten", "sem lactose"]

  nutrition_specialist:
    type: NutritionAgent
    config:
      role: "Especialista em Nutrição"
      goal: "Recomendar suplementos alimentares para necessidades específicas"
      backstory: |
        Nutricionista com experiência em suplementação alimentar e nutrição esportiva.
        Conhecimento especializado em formulações para diferentes objetivos nutricionais.
    tools:
      - nutrition_catalog
      - diet_analyzer
      - supplement_recommender
    plugins:
      - name: nutrition_advisor
        version: 1.2
        config:
          objectives: ["ganho muscular", "emagrecimento", "saúde geral", "performance"]
          nutritional_focus: ["proteínas", "carboidratos", "vitaminas", "antioxidantes"]
