account_1-00bfe67a: 0701Gio***
account_id: account_1
business_area: retail
description: "Configura\xE7\xE3o para Sandra Cosmeticos"
facebook_token: ''
instagram_token: ''
integrations:
  mcp:
    config:
      credential_ref: account_1-00bfe67a
      db: account_1
      url: http://localhost:8069
      username: giovano@sprintia.com.br
    type: odoo-mcp
  qdrant:
    collection: business_rules_account_1
  redis:
    prefix: account_1
name: Sandra Cosmeticos
openai_api_key: ''
qdrant_api_key: ''
