account_id: account_1
company_metadata:
  business_hours:
    days:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    end_time: '18:00'
    has_lunch_break: true
    lunch_break_end: '13:00'
    lunch_break_start: '12:00'
    saturday_end_time: '12:00'
    saturday_start_time: 08:00
    start_time: 09:00
  company_info:
    business_area: retail
    business_area_other: false
    company_name: Sandra Cosméticos
    company_values: ''
    description: TESTANDO 1234556
  customer_service:
    communication_style: friendly
    emoji_usage: none
    greeting_message: Testando sistema de visualização
  online_channels:
    facebook:
      mention_at_end: false
      url: false
    instagram:
      mention_at_end: true
      url: www.instagram/sandracosmeticos
    website:
      mention_at_end: true
      url: www.sandracosmeticos.com.br
  promotions:
    inform_at_start: true
description: TESTANDO 1234556
enabled_collections:
- business_rules
- products_informations
- support_documents
integrations:
  facebook:
    access_token_ref: fb_token_account_1
    app_id: '12345678910'
    app_secret_ref: fb_secret_account_1
  instagram:
    access_token_ref: ig_token_account_1
    client_id: '12345678910'
  mcp:
    config:
      credential_ref: account_1-00bfe67a
      db: account_1
      url: http://localhost:8069
      username: giovano@sprintia.com.br
    type: odoo-mcp
  mercado_livre:
    access_token_ref: ml_token_account_1
    app_id: '123456'
    client_secret_ref: ml_secret_account_1
  qdrant:
    collection: business_rules_account_1
  redis:
    prefix: account_1
name: Sandra Cosméticos
