account_id: account_1
credentials:
  account_1-00bfe67a: ENC:Z0FBQUFBQm9COVloN19tSFJaYS1lRDNUV3I0M19qbUNXN3U1NUJDc2Q4eUlsSHBhTFQ1eW5rbnVpZWhkMlZVUDIxODlxei1IYWZ1amw4VTlBT3lDU2VCZWJ0UFFsdlBzOEE9PQ==
  fb_secret_account_1: ENC:Z0FBQUFBQm9COVloSmRoekJTWEpTd3hCM0lQdko0WEVvSzNoRVdBT1ZKM1FORUstU2MzX0FISjZQcXlYNHYyalp6aVMwamJqRUs5ZklXai0xZ3V1TVpnU194blBvUnJiQ2c9PQ==
  fb_token_account_1: ENC:Z0FBQUFBQm9COVloMHppdmNfcE1lRTB6WVJkMHpaeWlqd0xqUFhzOVk5N2YxT1JJVjAxdXE0UHJYRllOU0FBUDViOGVPaFVYM1dVNFlmQ1VrMEc0cThOSmRiQ1BpdDFPd3c9PQ==
  ig_token_account_1: ENC:Z0FBQUFBQm9COVlodFJDNmxiQnNDM0hzZXlIcmR4dnBvWHF6NXhIaGFEWldUTzc0UjB6bnZocXlZN2oxSFBaNm1YbmRTYmZ6VU80dTJyUFdFbW1ZQmlndHVvTVpROFVGQmc9PQ==
  ml_secret_account_1: ENC:Z0FBQUFBQm9COVlocmxkdjJOR0JGanJaS19KUDIwQWFpSmlWZkJWQVNMSGFDQnZWQmpqOS1NdVpNN01UV283Zk9KOTNWS0Q0eVNGTkt4c19MQUp4aVdtSzh5TVc4ajVMdlE9PQ==
  ml_token_account_1: ENC:Z0FBQUFBQm9COVloeGVnc1dNWFA5Z2J6V2ZsVTYzUWZicWJ2UEhvaVZlNkNxekVVUmRMQTMtQlQ2T2NIMjUzbzlDN21MVXhPYW5nZTZKaGZWeHdnUExPOUhrQXAwM1FfSHc9PQ==
