account_id: account_1
credentials:
  account_1-00bfe67a: ENC:Z0FBQUFBQm9DQVl4S1RCWWF4VUhlWF9vcjdxQ1cySE5LblRFQThTZFlhUnZhT0NmMmEwMGtNamFTN1hJSjZsLU1aanBvWEhxTkl0WWdKeFJ2ZzVYTWIzWGl5R1NoSVVNU0E9PQ==
  fb_secret_account_1: ENC:Z0FBQUFBQm9DQVl4VWJ0d2ZfcGwxaElHcEs4YUx5bDd0YktTOUVfZ2hSNUtHNWU1UmxZSzJWRlRvMmo4LVY1c2FxRV9kNXBscTZJdWxJTkMzc2Rib1V4eURRcEQ5RHVQYXc9PQ==
  fb_token_account_1: ENC:Z0FBQUFBQm9DQVl4dTFpSk5iOHRwX1c1RWUxM3R6cEVKbDlKOHNPQ1FDYzFWRldmVHRVY2dHMzhqU0VNRVdIMU80b05sbTFOWkRRR3RBWUc1NGp1QTA1NnFKbHhTVF9aX0E9PQ==
  ig_token_account_1: ENC:Z0FBQUFBQm9DQVl4cnF0M0xlSVd0cWJtdUh2MEJaUU82cWFjY3pwa2daa0tDS013cHBKdXVZYUdKV0R0SjZBY0NPUFljWXl3dDNzWnJ2Zl84dTViUXhOb3k2WkNaNktSYkE9PQ==
  ml_secret_account_1: ENC:Z0FBQUFBQm9DQVl4NEcwVGdxbmIwZjg3YksyazBMQ3BvUzZaMmQydFEtem80NGl2bEJCaE8zTE1abmFpWlh1NktpY1ZBSjNfVXlnOHh1MmhxOVJ6T1Q3VmxxdmJOY1pzanc9PQ==
  ml_token_account_1: ENC:Z0FBQUFBQm9DQVl4ZTNOZVRjTG1RZEZpc2RDRWZhanR3dUxkWm5ubkgzYUJDdTZTVjZoblZIMk1WVlRjY2dMbm04VGRRaFJEYWo1Q3JBTG04anFrSURNN0t0cnROenR4WHc9PQ==
