account_id: account_1
credentials:
  account_1-00bfe67a: ENC:Z0FBQUFBQm9HWF9Gam5VSVdwMVlXVE41TTdZYVpuUmFZLWdEdjhyZlp2STI2NE5UVV9IVDFZYlNBR2JQYUxQSXJGek5ROVlwN3RCTjhCVUNaRWZ3eDFHWFRTOEVKaWVnc2c9PQ==
  fb_secret_account_1: ENC:Z0FBQUFBQm9HWF9GN1RXQ19MRGhKUnJ1VTk0QkJMR0hkNzFaYkxrZFdqQkgyYlpObENCb2dzYjR5Qnh6dzB5ZUdXRmhxVW9SZHBaNE4tOUp0MEVuclRoQUdUdDkxdmxHWHc9PQ==
  fb_token_account_1: ENC:Z0FBQUFBQm9HWF9Gc2FVY05sb3VhREdtUlU5V1AtSndHdGJjOVAzR0hCYnNKRlI0TzVHNVpHU0hBNVJjTE50bEk2M2tOb3ZNeGE5VG02b1B5R0JvTHRLSGdRRHZzMXdwR0E9PQ==
  ig_token_account_1: ENC:Z0FBQUFBQm9HWF9GU0hVVWNsX0VtQWNNSkdWeVM3OU0zMGVrOG5haUJXSWZ2dnN5ZldPVDcwZ1plWHZkR1YwakY3cGJoOEc1V2ZldFdreW53RlYyV1pJZjZaRU1NY0NGMkE9PQ==
  ml_secret_account_1: ENC:Z0FBQUFBQm9HWF9GaUt0TDduV0VnX2tpaFo0SUhLalZWM0V5c2l2NHRDRDNtNVZsS1JBeS01d1dkcWVIRzhkRHZuZkY1c0E4Z1F2UVlmLVk3aFJIZnBhdXR6cHVkVHRfeHc9PQ==
  ml_token_account_1: ENC:Z0FBQUFBQm9HWF9GTzNLZGRJS3JIVC1JQ3NMc0lZQ1VEUDhMbjh5RnBNZTVUZTRsY1JEVFdTbW56UGhmTW5hN2RTaEFNOHFoVmJjWW14cXAzcGhpYWt2SllsanBjbkwwOUE9PQ==
