account_id: account_1
credentials:
  account_1-00bfe67a: 0701Gio***
  fb_secret_account_1: '123456'
  fb_token_account_1: '123456'
  ig_token_account_1: '123456'
  ml_secret_account_1: '123456'
  ml_token_account_1: '123456'
