## Configurações Base para Ferramentas
## Este arquivo define as ferramentas disponíveis para os agentes no sistema
## Cada domínio pode estender ou sobrescrever estas configurações

version: 2.1

# Definição central de todas as ferramentas disponíveis no sistema
tools:
  # Ferramentas de busca
  basic_search:
    name: "Busca Básica"
    description: "Realiza buscas simples em texto"
    class: "src.tools.search.BasicSearchTool"
    parameters:
      max_results: 10
      use_fuzzy: true
  
  # Ferramentas de consulta a dados
  data_query:
    name: "Consulta de Dados"
    description: "Consulta dados em diferentes fontes de forma unificada"
    class: "src.tools.data.DataQueryTool"
    parameters:
      timeout: 30
      cache_results: true
  
  # Ferramentas de banco de dados
  database_query:
    name: "Consulta SQL"
    description: "Executa consultas SQL no banco de dados"
    class: "src.tools.database.DatabaseQueryTool"
    parameters:
      max_rows: 1000
      safe_mode: true
  
  # Ferramentas de busca vetorial
  vector_search:
    name: "Busca Vetorial"
    description: "Realiza buscas semânticas no banco de dados vetorial"
    class: "src.tools.vector.VectorSearchTool"
    parameters:
      engine: "qdrant"
      similarity_threshold: 0.7
      max_results: 20
  
  # Ferramentas de cache
  cache_manager:
    name: "Gerenciador de Cache"
    description: "Gerencia o cache de dados para otimizar performance"
    class: "src.tools.cache.CacheManagerTool"
    parameters:
      default_ttl: 600
      compression: true
  
  # Ferramentas de memória
  memory_retrieval:
    name: "Recuperação de Memória"
    description: "Recupera informações da memória do sistema"
    class: "src.tools.memory.MemoryRetrievalTool"
    parameters:
      context_window: 5
      recency_weight: 0.7
  
  # Ferramentas específicas para vendas
  product_catalog:
    name: "Catálogo de Produtos"
    description: "Acessa informações do catálogo de produtos"
    class: "src.tools.sales.ProductCatalogTool"
    parameters:
      include_images: true
      include_prices: true
  
  # Ferramentas de análise
  sales_analytics:
    name: "Análise de Vendas"
    description: "Análises e estatísticas sobre vendas"
    class: "src.tools.analytics.SalesAnalyticsTool"
    parameters:
      period: "monthly"
      include_graphs: true
