## Configurações Base para Agentes
## Este arquivo define características comuns a todos os agentes do sistema
## Estas configurações podem ser sobrescritas nos domínios específicos

version: 2.1

# Configurações padrão dos agentes
agents:
  # Agente Base - Serve como template para outros agentes
  base_agent:
    description: "Configuração base para todos os agentes"
    memory_settings:
      ttl: 3600  # Tempo de vida em segundos (1 hora)
      max_tokens: 4000
    tools:
      - basic_search
      - memory_retrieval
      - data_query

  # DataProxyAgent - Agente Central para acesso a dados
  data_proxy:
    description: "Agente de proxy para acesso centralizado a dados"
    role: "Intermediário para acesso a dados"
    goal: "Fornecer acesso unificado e seguro a todos os serviços de dados"
    backstory: "Componente central da arquitetura que gerencia todo acesso a dados do sistema"
    tools:
      - database_query
      - vector_search
      - cache_manager
    memory_settings:
      ttl: 7200  # 2 horas em segundos
      priority: high
      
# Configurações de serviços comuns a todos os agentes
services:
  database:
    connection_pool_size: 10
    timeout: 30
    retry_attempts: 3
  
  redis:
    cache_ttl: 600  # 10 minutos em segundos
    max_memory: "512mb"
  
  qdrant:
    distance_threshold: 0.75
    max_results: 50
