# Configuração de mapeamento para o ChatwootAI
# Este arquivo define como as contas (accounts) e caixas de entrada (inboxes) do Chatwoot
# são mapeadas para domínios e clientes específicos no sistema.

# Mapeamento de account_id para domínio e cliente
# Formato: "account_id": {"domain": "nome_do_domínio", "account_id": "id_do_cliente"}
# Quando uma mensagem chega de uma conta específica, o sistema identifica exatamente qual cliente e domínio usar
accounts:
  "1": {"domain": "cosmetics", "account_id": "account_1"}  # Beleza Natural Ltda.
  "2": {"domain": "cosmetics", "account_id": "account_2"}  # Glamour Cosméticos S.A.
  "3": {"domain": "health", "account_id": "account_3"}     # Vida Saudável Farmácias
  "4": {"domain": "retail", "account_id": "account_4"}     # SuperCompras Varejo
  "5": {"domain": "furniture", "account_id": "account_2"}  # Móveis Elegantes
  # Adicione novos mapeamentos conforme necessário

# Mapeamento de inbox_id para domínio e cliente (fallback)
# Usado quando o account_id não resolve para um cliente específico
inboxes:
  "101": {"domain": "cosmetics", "account_id": "account_1"}  # Inbox do WhatsApp da Beleza Natural
  "102": {"domain": "cosmetics", "account_id": "account_2"}  # Inbox do Instagram da Glamour Cosméticos
  "201": {"domain": "health", "account_id": "account_3"}     # Inbox do WhatsApp da Vida Saudável
  "301": {"domain": "retail", "account_id": "account_4"}     # Inbox do Facebook do SuperCompras
  "401": {"domain": "furniture", "account_id": "account_2"}  # Inbox do WhatsApp dos Móveis Elegantes
  # Adicione novos mapeamentos conforme necessário

# Lista de clientes para referência fácil
clients:
  "account_1": {"name": "Beleza Natural Ltda.", "domain": "cosmetics"}
  "account_2": {"name": "Glamour Cosméticos S.A.", "domain": "cosmetics"}
  "account_3": {"name": "Vida Saudável Farmácias", "domain": "health"}
  "account_4": {"name": "SuperCompras Varejo", "domain": "retail"}
  "furniture_account_2": {"name": "Móveis Elegantes", "domain": "furniture"}

# Configurações adicionais para o webhook handler
webhook_settings:
  # Tempo máximo (em segundos) para processar um webhook antes de timeout
  processing_timeout: 30

  # Número máximo de tentativas para processar um webhook em caso de falha
  max_retries: 3

  # Habilitar log detalhado para webhooks (true/false)
  detailed_logging: true
