# Credenciais para todos os accounts
# Este arquivo é gerenciado pelo módulo ai_credentials_manager

account_1:
  account_1-00bfe67a: "admin"  # Senha para o Odoo
  openai_api_key: ""
  qdrant_api_key: ""
  facebook_token: ""
  instagram_token: ""
