version: '3.8'

networks:
  chatwoot_network:
    driver: overlay
    attachable: true

services:
  webhook_server:
    image: ${DOCKER_IMAGE:-chatwootai:latest}
    networks:
      - chatwoot_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      labels:
        - "traefik.enable=false"  # Não expor externamente via Traefik
    command: python -m src.api.webhook_server
    environment:
      - CHATWOOT_API_KEY=${CHATWOOT_API_KEY}
      - CHATWOOT_BASE_URL=http://chatwoot_web:3000/api/v1  # URL interna do Docker
      - CHATWOOT_ACCOUNT_ID=${CHATWOOT_ACCOUNT_ID:-1}
      - WEBHOOK_PORT=8001
      - WEBHOOK_AUTH_TOKEN=${WEBHOOK_AUTH_TOKEN:-efetivia_webhook_secret_token_2025}
      - POSTGRES_DB=${POSTGRES_DB:-chatwootai}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres_password}
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./:/app  # Montar o código-fonte para desenvolvimento
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
