accounts:
  '1':
    name: Beleza Natural Ltda.
    test_messages:
    - "Ol\xE1, voc\xEAs t\xEAm creme para as m\xE3os?"
    - "Qual o pre\xE7o do creme hidratante?"
    - "Voc\xEAs entregam em S\xE3o Paulo?"
  '2':
    name: "Glamour Cosm\xE9ticos S.A."
    test_messages:
    - "Bom dia, voc\xEAs t\xEAm protetor solar?"
    - Qual o melhor shampoo para cabelos cacheados?
    - "Voc\xEAs t\xEAm produtos veganos?"
  '3':
    name: "Vida Saud\xE1vel Farm\xE1cias"
    test_messages:
    - "Bom dia, preciso de um rem\xE9dio para dor de cabe\xE7a"
    - "Voc\xEAs t\xEAm vitamina C?"
    - "Qual o hor\xE1rio de funcionamento da farm\xE1cia?"
expected_responses:
  max_retries: 3
  timeout: 10
test_timeout: 30
webhook:
  base_inbox_id: 100
  url: http://localhost:8000/webhook
