online_channels:
  instagram:
    mention_at_end: true
    url: www.instagram/sandracosmeticos
  website:
    mention_at_end: true
    url: www.sandracosmeticos.com.br
promotions:
  inform_at_start: true
style:
  emojis:
    enabled: false
    frequency: minimal
  greeting:
    enabled: true
    message: Olá! Obrigada por entar em contato com a Sandra Cosméticos, em que posso
      te ajudar hoje?
  tone:
    formal: 5
    friendly: 2
    technical: 3
