## Configuração para o Cliente 2 - Domínio de Cosméticos
## Este arquivo define todas as configurações específicas para o Cliente 2 no domínio de cosméticos

version: "2.1"
metadata:
  domain: cosmetics
  client_id: "client_2"
  client_name: "Glamour Cosméticos S.A."
  description: "Rede de lojas especializada em produtos de beleza premium"
  inherit: "_base"  # Herda configurações base

# Configurações específicas dos agentes para o domínio de cosméticos
agents:
  sales_expert:
    type: SalesAgent
    config:
      role: "Consultor de Beleza Premium"
      goal: "Auxiliar clientes na escolha de produtos cosméticos premium"
      backstory: |
        Especialista em produtos de beleza de alta qualidade com experiência em marcas internacionais.
        Você trabalhou nas principais marcas de luxo e entende as necessidades de clientes exigentes.
    tools:
      - premium_product_catalog
      - skin_analyzer
      - beauty_recommender
    plugins:
      - name: luxury_cosmetics_advisor
        version: 1.3
        config:
          skin_types: ["normal", "seca", "oleosa", "mista", "sensível"]
          concern_areas: ["acne", "rugas", "manchas", "hidratação", "rejuvenescimento"]

  makeup_specialist:
    type: ProductAgent
    config:
      role: "Especialista em Maquiagem"
      goal: "Recomendar produtos de maquiagem para ocasiões específicas"
      backstory: |
        Maquiador(a) profissional com experiência em eventos de moda e beleza.
        Conhecimento especializado em técnicas de maquiagem para diferentes tons de pele.
    tools:
      - makeup_catalog
      - color_matcher
      - occasion_recommender
    plugins:
      - name: makeup_artist
        version: 1.1
        config:
          skin_tones: ["clara", "média", "morena", "negra"]
          occasions: ["casual", "trabalho", "festa", "casamento"]
