version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai-qdrant
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - 6333:6333
      - 6334:6334  # gRPC port
    networks:
      - ai-stack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true
      # Configurações opcionais
      # - QDRANT_TELEMETRY_DISABLED=true  # Desabilitar telemetria
      # - QDRANT_LOG_LEVEL=INFO  # Nível de log (DEBUG, INFO, WARN, ERROR)

networks:
  ai-stack:
    external: true

volumes:
  qdrant_data:
    driver: local
