version: '3.8'

services:
  mcp-qdrant:
    build:
      context: ../../mcp-qdrant
      dockerfile: Dockerfile
    container_name: mcp-qdrant
    restart: unless-stopped
    environment:
      - QDRANT_URL=http://ai-qdrant:6333
      - COLLECTION_NAME=ai_memories
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - FASTMCP_PORT=8000
      - FASTMCP_HOST=0.0.0.0
    command: ["uvx", "mcp-server-qdrant", "--transport", "sse"]
    ports:
      - 8003:8000
    networks:
      - ai-stack
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  ai-stack:
    external: true
