# Configuração para o domínio de móveis
version: "1.0"
name: "Móveis"
description: "Domínio para lojas de móveis"
domain: "furniture"

# Configurações gerais do domínio
settings:
  language: "pt_BR"
  currency: "BRL"
  timezone: "America/Sao_Paulo"

  # Categorias de produtos padrão
  product_categories:
    - "Sala"
    - "Quarto"
    - "Cozinha"
    - "Escritório"
    - "Decoração"
    - "Jardim"

  # Configurações de atendimento padrão
  customer_service:
    business_hours:
      - "Segunda a Sexta: 09:00 - 18:00"
      - "Sábado: 09:00 - 13:00"
